imu_processor_node:
  ros__parameters:
    # 角速度协方差 (必须全部使用浮点表示)
    angular_velocity_covariance: [1.3e-6, 0.0, 0.0, 0.0, 1.3e-6, 0.0, 0.0, 0.0, 1.3e-6]
    
    # 线加速度协方差
    linear_acceleration_covariance: [4.0e-4, 0.0, 0.0, 0.0, 4.0e-4, 0.0, 0.0, 0.0, 4.0e-4]
    
    # 姿态协方差
    orientation_covariance: [0.05, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.05]
    
    # 字符串参数
    frame_id: "imu_link"

    # 零飘检测
    calibrate_flag: false